// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TutorialController from "./tutorial_controller"
application.register("tutorial", TutorialController)

import SimulationResultController from "./simulation_result_controller"
application.register("simulation-result", SimulationResultController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import DicePreviewController from "./dice_preview_controller"
application.register("dice-preview", DicePreviewController)

import DiceCollectionController from "./dice_collection_controller"
application.register("dice-collection", DiceCollectionController)

import RewardTicketController from "./reward_ticket_controller"
application.register("reward-ticket", RewardTicketController)

import CompletionPopupController from "./completion_popup_controller"
application.register("completion-popup", CompletionPopupController)

import AutoShowToastController from "./auto_show_toast_controller"
application.register("auto-show-toast", AutoShowToastController)

import CollectionTutorialController from "./collection_tutorial_controller"
application.register("collection-tutorial", CollectionTutorialController)
