// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TutorialController from "./tutorial_controller"
application.register("tutorial", TutorialController)

import SimulationResultController from "./simulation_result_controller"
application.register("simulation-result", SimulationResultController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import DicePreviewController from "./dice_preview_controller"
application.register("dice-preview", DicePreviewController)
